connections:
  - conn_id: postgres_conn
    conn_type: postgres
    host: localhost
    schema:
    login: postgres
    password: postgres
    port: 5432
    extra:
  - conn_id: snowflake_conn
    conn_type: snowflake
    host: https://gp21411.us-east-1.snowflakecomputing.com
    port: 443
    login: $SNOWFLAKE_ACCOUNT_NAME
    password: $SNOWFLAKE_PASSWORD
    schema: ASTROFLOW_CI
    extra:
      account: "gp21411"
      region: "us-east-1"
      role: "AIRFLOW_TEST_USER"
      warehouse: DEMO
      database: SANDBOX
  - conn_id: bigquery
    conn_type: bigquery
    description: null
    extra: null
    host: "astronomer-dag-authoring"
    login: null
    password: null
    port: null
    schema: null
  - conn_id: sqlite_conn
    conn_type: sqlite
    host: ////tmp/sqlite.db
    schema:
    login:
    password:
  - conn_id: gcp_conn
    conn_type: google_cloud_platform
    description: null
    extra: null
  - conn_id: google_cloud_default
    conn_type: google_cloud_platform
    description: null
    extra: null
  - conn_id: aws_conn
    conn_type: aws
    description: null
    extra: null
  - conn_id: aws_default
    conn_type: aws
    login: $AIRFLOW_CONN_AWS_DEFAULT_LOGIN
    password: $AIRFLOW_CONN_AWS_DEFAULT_PASSWORD
    description: null
    extra: null