version = 1

test_patterns = [
  "python-sdk/tests/**",
  "python-sdk/test-docker/**",
  "sql-cli/tests/**"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
