version = 1

test_patterns = [
  "python-sdk/tests/**",
  "python-sdk/tests_integration/**",
  "python-sdk/test-docker/**",
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
