---
default_stages: [commit, push]
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3
minimum_pre_commit_version: "1.20.0"
repos:
  - repo: meta
    hooks:
      - id: identity
      - id: check-hooks-apply
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
      - id: blacken-docs
        alias: black
        additional_dependencies: [black==21.7b0]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
      - id: isort
        name: Run isort to sort imports in Python files
        args: [ "--profile", "black" ]
        files: \.py$
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: ''  # Use the sha / tag you want to point at
      hooks:
      -   id: mypy
          additional_dependencies: [types-PyYAML]
  -   repo: https://github.com/asottile/pyupgrade
      rev: v2.31.0
      hooks:
      -   id: pyupgrade
          args: [--py37-plus]
