coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        only_pulls: true
flags:
  UTO:
    paths: #note, accepts globs, not regexes
      - universal_transfer_operator/src
    carryforward: true
  PythonSDK:
    paths:
      - python-sdk/src
    carryforward: true
