workflow:
  description: "Sample workflow used to load data from a CSV file into a SQLite database"
  schedule: "@daily"
  start_date: "2015-12-1"
  is_paused_upon_creation: false
  tags:
    - SQL
    - example 
