name: "Astro Deploy"
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      git_rev:
        description: 'The git revision to deploy'
        required: false
        default: ''

      environment_to_deploy:
        description: 'astro cloud deployment to deploy to'
        required: true
        type: choice
        options:
          - both
          - astro-sdk-integration-tests
          - astro-sdk-integration-tests-on-KE
      dags_to_trigger_after_deployment:
        description: |
          Comma separated list of dag_ids to trigger after deployment
          (e.g. "example_mssql_transform, example_load_file")
        required: false
        type: string
        default: ''
  workflow_call:
    inputs:
      git_rev:
        description: 'The git revision to deploy'
        type: string
        required: false
        default: ''
      environment_to_deploy:
        description: 'astro cloud deployment to deploy to'
        required: true
        type: string
        default: both
      dags_to_trigger_after_deployment:
        description: |
          Comma separated list of dag_ids to trigger after deployment
          (e.g. "example_mssql_transform, example_load_file")
        required: false
        type: string
        default: ''
    secrets:
      astro_subdomain:
        description: 'astro cloud subdomain'
        required: true
      deployment_id:
        description: 'astro cloud deployment_id'
        required: true
      astronomer_key_id:
        description: 'astro cloud astronomer_key_id'
        required: true
      astronomer_key_secret:
        description: 'astro cloud astronomer_key_secret'
        required: true
      organization_id:
        description: 'astro cloud organization_id'
        required: true
      bearer_token:
        description: 'workspace bearer token'
        required: true
      docker_registry:
        description: 'docker registry'
        required: true
      SLACK_WEBHOOK_URL:
        description: 'slack webhook'
        required: true




jobs:
  deploy-to-astro-sdk-integration-tests:
    if: |
      contains(fromJSON('["both", "astro-sdk-integration-tests"]'), inputs.environment_to_deploy) ||
      github.event_name == 'schedule'
    uses: ./.github/workflows/reuse-wf-deploy-to-astro-cloud.yaml
    with:
      git_rev: ${{ inputs.git_rev }}
      environment_to_deploy: 'astro-sdk-integration-tests'
    secrets:
      docker_registry:  ${{ secrets.ASTRO_DOCKER_REGISTRY }}
      organization_id:  ${{ secrets.ORGANIZATION_ID }}
      deployment_id:  ${{ secrets.ASTRO_DEPLOYMENT_ID }}
      astronomer_key_id: ${{ secrets.ASTRO_KEY_ID }}
      astronomer_key_secret: ${{ secrets.ASTRO_KEY_SECRET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  wait-for-deployment-to-be-ready-and-trigger-dags-for-astro-sdk-integration-tests:
    if: |
      github.event_name == 'schedule' ||
      (github.event_name == 'workflow_dispatch' && inputs.dags_to_trigger_after_deployment != '')
    needs: deploy-to-astro-sdk-integration-tests
    uses: ./.github/workflows/reuse-wf-trigger-dag.yaml
    with:
      git_rev: ${{ inputs.git_rev }}
      dags_to_trigger_after_deployment: ${{ inputs.dags_to_trigger_after_deployment }}
    secrets:
      astro_subdomain: ${{ secrets.ASTRO_SUBDOMAIN }}
      deployment_id: ${{ secrets.ASTRO_DEPLOYMENT_ID }}
      astronomer_key_id: ${{ secrets.ASTRO_KEY_ID }}
      astronomer_key_secret: ${{ secrets.ASTRO_KEY_SECRET }}
      organization_id: ${{ secrets.ORGANIZATION_ID }}
      bearer_token: ${{ secrets.BEARER_TOKEN }}

  deploy-to-astro-sdk-integration-tests-on-KE:
    if: |
      contains(fromJSON('["both", "astro-sdk-integration-tests-on-KE"]'), inputs.environment_to_deploy) ||
      github.event_name == 'schedule'
    uses: ./.github/workflows/reuse-wf-deploy-to-astro-cloud.yaml
    with:
      git_rev: ${{ inputs.git_rev }}
      environment_to_deploy: 'astro-sdk-integration-tests-on-KE'
    secrets:
      docker_registry:  ${{ secrets.ASTRO_DOCKER_REGISTRY }}
      organization_id:  ${{ secrets.ORGANIZATION_ID }}
      deployment_id:  ${{ secrets.ASTRO_DEPLOYMENT_ID_KE }}
      astronomer_key_id: ${{ secrets.ASTRO_KEY_ID_KE }}
      astronomer_key_secret: ${{ secrets.ASTRO_KEY_SECRET_KE }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  wait-for-deployment-to-be-ready-and-trigger-dags-for-astro-sdk-integration-tests-on-KE:
    if: |
      github.event_name == 'schedule' ||
      (github.event_name == 'workflow_dispatch' && inputs.dags_to_trigger_after_deployment != '')
    needs: deploy-to-astro-sdk-integration-tests-on-KE
    uses: ./.github/workflows/reuse-wf-trigger-dag.yaml
    with:
      git_rev: ${{ inputs.git_rev }}
      dags_to_trigger_after_deployment: ${{ inputs.dags_to_trigger_after_deployment }}
    secrets:
      astro_subdomain: ${{ secrets.ASTRO_SUBDOMAIN }}
      deployment_id: ${{ secrets.ASTRO_DEPLOYMENT_ID_KE }}
      astronomer_key_id: ${{ secrets.ASTRO_KEY_ID_KE }}
      astronomer_key_secret: ${{ secrets.ASTRO_KEY_SECRET_KE }}
      organization_id: ${{ secrets.ORGANIZATION_ID }}
      bearer_token: ${{ secrets.BEARER_TOKEN }}
