---
name: Test providers RC releases

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 0,12 * * *"
  workflow_dispatch:
    inputs:
      rc_testing_branch:
        # If a branch is given, the workflow will use it for deployment and testing.
        # If no branch is provided, the workflow will create a new rc testing branch
        # for deployment and testing.
        description: |
          rc_testing_branch: existing testing branch
          (Either rc_testing_branch or issue_url is required, and you cannot give both.)
        required: false
        default: ""
      issue_url:
        description: |
          issue_url: the GitHub issue URL that tracks the status of Providers release
          (Either rc_testing_branch or issue_url is required, and you cannot give both.)
        required: false
      base_git_rev:
        description: "The base git revision to test Providers RCs"
        required: false
        type: string
        default: "main"
defaults:
  run:
    working-directory: python-sdk

jobs:
  check-airflow-provider-rc-release:
    uses: astronomer/astronomer-providers/.github/workflows/reuse-wf-check-rc-release.yaml@main
    with:
      rc_testing_branch: ${{ inputs.rc_testing_branch }}
      issue_url: ${{ inputs.issue_url }}
      base_git_rev: ${{ inputs.base_git_rev }}
      git_email: "airflow-oss-bot@astronomer.io"
      git_username: "airflow-oss-bot"
      working_directory: "python-sdk"
    secrets:
      BOT_ACCESS_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}

  deploy-and-trigger-example-dag:
    needs: check-airflow-provider-rc-release
    if: |
      always() &&
      needs.check-airflow-provider-rc-release.outputs.rc_issue_url != '' || ${{ inputs.issue_url }} != ''
    uses:  ./.github/workflows/ci-astro-deploy.yml
    with:
       environment_to_deploy: "both"
       dags_to_trigger_after_deployment: "example_master_dag"
       git_rev: ${{ needs.check-airflow-provider-rc-release.outputs.rc_testing_branch }}
    secrets: inherit
